version: '3.3'

services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./python-mysql-data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Sas95204051
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerce
  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    tty: true
    links:
      - db
    environment:
      - DJANGO_DB=ecommerce
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWD=Sas95204051
      - DJANGO_HOST=db
      - DJANGO_DB_PORT=3306
