# Generated by Django 3.1 on 2020-05-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200426_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ehDestaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='ehProdutoAtivo',
            field=models.BooleanField(default=True),
        ),
    ]
